# Generated by Django 4.0.6 on 2022-07-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigns',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
