# Generated by Django 4.0.6 on 2022-07-20 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_alter_campaigns_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaigns',
            options={'ordering': ('-created_at',), 'verbose_name': 'Campaign', 'verbose_name_plural': 'Campaigns'},
        ),
    ]
